config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => "/admin", as: "rails_admin"
  mount Ckeditor::Engine => "/ckeditor"
  root "static_pages#home"
  devise_for :users, controllers: {registrations: "registrations",
    omniauth_callbacks: "omniauth_callbacks"}

  resources :users, only: [:show] do
    member do
      get :following, :followers
    end
  end

  resources :posts, except: [:new, :edit, :index] do
    resources :comments, except: [:index, :new, :show]
  end

  resources :relationships, only: [:create, :destroy]
  resources :tags, only: :show
  resources :posts_manager, only: [:index, :create, :update] do
    collection do
      delete :destroy_posts
    end
  end
  get "/feed", to: "users#feed"
  post "search-post", to: "search#search_post"
  post "search-user", to: "search#search_user"
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :content, presence: true
  validates :post, presence: true
  validates :user, presence: true

  paginates_per Settings.comment.per_page

  scope :order_asc, ->{order created_at: :asc}
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  include ResourceComment
  load_and_authorize_resource

  def create
    @comment = current_user.comments.build comment_params

    if @comment.save
      @post = @comment.post
      comment_js t("success"), 200

      @post.user.send_comment_notify_email(@comment) unless
        current_user == @post.user
    else
      comment_respond
    end
  end

  def edit
    comment_respond
  end

  def update
    if @comment.update_attributes comment_params
      comment_js t(".success"), 200
    else
      comment_respond
    end
  end

  def destroy
    @post = @comment.post
    if @comment.destroy
      comment_js t(".success"), 200
    else
      comment_respond
    end
  end
end

app/views/comments/_comment.html.erb
<div id="comment-<%= comment.id %>" class = "comment">
  <%= image_tag post.user.avatar.url, class: "avatar-header" %>
  <span class="user"><%= link_to comment.user.full_name, comment.user %></span>
  <span class="timestamp">
    <i class="created-at"><%= comment.created_at %></i>&nbsp;&nbsp;
    <% if can? :update, comment %>
      <%= link_to t(".edit"), edit_post_comment_path(post, comment),
        remote: true, class: "edit-comment" %> |
    <% end %>
    <% if can? :destroy, comment %>
      <%= link_to t(".delete"), post_comment_path(post, comment),
        method: :delete, data: {confirm: t("comments.sure")}, remote: true,
        class: "user-delete" %>
    <% end %>
  </span>
  <p class="row content-comment", data-id = "<%= comment.id %>">
    <span><%= comment.content %></span>
  </p>
</div>

app/views/comments/_comment_form.html.erb
<%= form_for comment, url: post_comments_path(post, comment), remote: true do |f| %>
  <%= f.hidden_field :post_id, value: post.id %>
  <%= render "shared/error_messages", object: f.object %>
  <div class="field col-md-offset-1 comment-form">
    <%= f.text_field :content, placeholder: t(".comment"),
      class: "form-control comment-content-input"%>
    <div>
      <%= f.submit t(".comment"), class: "submit-comment btn-primary" %>
    </div>
  </div>
<% end %>

app/views/comments/_form_edit.html.erb
<div class="content-comment" data-id="<%= comment.id %>">
  <%= form_for comment, url: post_comment_path(comment.post, comment),
    remote: true, class: "edit-comment-form" do |f| %>
    <%= f.text_field :content, class: "form-control edit-content" %>
    <%= f.button t("comments.update"), type: "submit",
      class: "update-comment btn-primary " %>
  <% end %>
</div>

app/views/comments/_number_comments.html.erb
<% if post.comments.any? %>
  <%= link_to t(".comments", number_comments: post.comments.size), post,
    class: "number-comment-block" %>
<% end %>

app/views/comments/_update.html.erb
<%= comment.content %>

app/views/comments/create.js.erb
<% if @status == 200 %>
  $('.list-comments-' + '<%= @post.id %>')
    .append('<%= escape_javascript render('comments/comment',comment: @comment,\
    post: @post) %>');
  $('.number-comments-<%= @post.id %>')
    .html('<%= escape_javascript render('comments/number_comments',\
    post: @post) %>');
  $('.comment-content-input').val('');
<% else %>
  alert('<%= t "comments.create.has_error" %>');
<% end %>

app/views/comments/destroy.js.erb
<% if @status == 200 %>
  $('.user-delete').bind('ajax:success', function(){
    $('#comment-<%= @comment.id%>').closest('div').fadeOut();
    $('.number-comments-<%= @post.id %>')
      .html('<%= escape_javascript render('comments/number_comments',\
      post: @post) %>');
  });
<% else %>
  alert('<%= t "comments.destroy.has_error" %>');
<% end %>

app/views/comments/edit.js.erb
$('.edit-comment').bind('ajax:success', function(){
  $('.content-comment[data-id=<%= @comment.id %>]')
    .html("<%= escape_javascript render("comments/form_edit",\
      comment: @comment) %>");
});

app/views/comments/update.js.erb
<% if @status == 200 %>
  $('.content-comment[data-id=<%= @comment.id %>]')
    .html('<%= escape_javascript render('comments/update',\
    comment: @comment) %>');
<% else %>
  alert('<%= t "comments.update.has_error" %>');
<% end %>