config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => "/admin", as: "rails_admin"
  mount Ckeditor::Engine => "/ckeditor"
  root "static_pages#home"
  devise_for :users, controllers: {registrations: "registrations",
    omniauth_callbacks: "omniauth_callbacks"}

  resources :users, only: [:show] do
    member do
      get :following, :followers
    end
  end

  resources :posts, except: [:new, :edit, :index] do
    resources :comments, except: [:index, :new, :show]
  end

  resources :relationships, only: [:create, :destroy]
  resources :tags, only: :show
  resources :posts_manager, only: [:index, :create, :update] do
    collection do
      delete :destroy_posts
    end
  end
  get "/feed", to: "users#feed"
  post "search-post", to: "search#search_post"
  post "search-user", to: "search#search_user"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :post_tags, dependent: :destroy
  has_many :posts, through: :post_tags

  scope :popular, lambda{
    joins(:post_tags).group(:id).order("count(post_id) DESC")
      .limit Settings.tag.popular.limit
  }
  scope :months_before, lambda{|current_time|
    where("created_at < ? AND created_at > ?", current_time, current_time-60*60*24*30)
  }

  validates :name, presence: true, length: {maximum: Settings.tag.max_length}
end

app/controllers/posts_manager_controller.rb
class PostsManagerController < ApplicationController
  before_action :verify_admin
  before_action :load_post, only: :update
  before_action :post_search, only: :index

  def index
    @post = current_user.posts.build
    if params[:post_key] || params[:user_key]
      @posts = @search_result.includes(:user).page(params[:page])
              .per Settings.post.per_page

      respond_to do |format|
        format.html{render :index}
        format.csv{send_data Post.to_csv(@search_result.includes(:user))}
        format.js
      end
    else
      @posts = Post.select_order_desc.includes(:user).page(params[:page])
              .per Settings.post.per_page
    end
  end

  def create
    @post = current_user.posts.build post_params
    if @post.save
      post_massage 200
    end
    post_respond
  end

  def update
    if @post.update_attributes post_params
      post_massage 200
    end
    post_respond
  end

  def destroy_posts
    @post_ids = params[:post_ids]
    if Post.bulk_destroy @post_ids
      post_massage 200
    end
    respond_to do |format|
      format.js
    end
  end

  private

  def verify_admin
    return if current_user.try :admin?
    flash[:danger] = t "posts_manager.permission_denied"
    redirect_to root_path
  end

  def post_params
    params.require(:post).permit :title, :content, :post_ids
  end

  def load_post
    @post = Post.find_by id: params[:id]
    return if @post
    render file: "public/404"
  end

  def post_search
    @post_key = params[:post_key]
    @user_key = params[:user_key]
    @search_result = Post.advanced_search "%#{@post_key}%", "%#{@user_key}%"
  end

  def post_massage status
    @status = status
  end

  def post_respond
    respond_to do |format|
      format.js
    end
  end
end

app/views/posts_manager/_edit.html.erb
<div class="modal fade" id="post-edit-<%= post.id %>" tabindex="-1"
   role="dialog" aria-labelledby="post-edit-<%= post.id %>-label" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-body">
        <%= form_for post, url: posts_manager_path(post), remote: true do |f| %>
          <div class="field">
            <%= f.label t(".title") %> <span class="require">*</span>
            <%= f.text_field :title, class: "form-control" %><br/>
            <%= f.label t(".content") %> <span class="require">*</span>
            <%= f.text_area :content, class: "ckeditor" %><br/>
          </div>
          <div class="show-errors-<%= post.id %> error-explanation"></div>
          <div><%= f.submit t(".edit"), class: "btn edit-post-btn btn-orange" %></div>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn" data-dismiss="modal"><%= t ".close" %></button>
      </div>
    </div>
  </div>
</div>

app/views/posts_manager/_modal_list.html.erb
<% posts.each do |post| %>
  <%= render "edit", post: post %>
  <%= render "show", post: post %>
<% end %>

app/views/posts_manager/_new.html.erb
<div class="modal fade" id="post-new" tabindex="-1"
   role="dialog" aria-labelledby="post-new %>-label" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-body">
        <%= form_for post, url: posts_manager_index_path, remote: true do |f| %>
          <div class="field">
            <%= f.label t(".title") %> <span class="require">*</span>
            <%= f.text_field :title, placeholder: t(".title"), class: "form-control post-title" %><br/>
            <%= f.label t(".content") %> <span class="require">*</span>
            <%= f.text_area :content, class: "ckeditor post-content" %><br/>
          </div>
          <div class="show-errors-create error-explanation"></div>
          <div><%= f.submit t(".create"), class: "btn edit-post-btn btn-orange" %></div>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn" data-dismiss="modal"><%= t ".close" %></button>
      </div>
    </div>
  </div>
</div>

app/views/posts_manager/_paginate.html.erb
<%= paginate posts, theme: "twitter-bootstrap-3", remote: true %>

app/views/posts_manager/_post.html.erb
<tr id="post-detail-<%= post.id %>" class="posts">
  <td class="data title-<%= post.id %>"><%= post.title %></td>
  <td class="data content-<%= post.id %>"><%= post.content.html_safe %></td>
  <td class="data user-<%= post.id %>"><%= post.user.full_name %></td>
  <td class="data post-id"><%= post.id %></td>
  <td class="show-btn">
    <%= link_to "#show-post-#{post.id}", class: "btn btn-link", data: { toggle: "modal" } do %>
      <i class="glyphicon glyphicon-eye-open"></i>
    <% end %>
  </td>
  <td class="edit-btn">
    <%= link_to "#post-edit-#{post.id}", class: "btn btn-link", data: { toggle: "modal" } do %>
      <i class="glyphicon glyphicon-pencil"></i>
    <% end %>
  </td>
  <td class="data check-box-<%= post.id %>">
    <%= check_box_tag 'post_ids[]', post.id, false, class: "check-box-field" %>
  </td>
</tr>

app/views/posts_manager/_post_list.html.erb
<% posts.each do |post| %>
  <%= render "post", post: post %>
<% end %>

app/views/posts_manager/_search_form.html.erb
<%= form_tag posts_manager_index_path, method: :get, remote: true, class: "posts-manager-search" do %>
  <%= text_field_tag :post_key, @post_key, placeholder: t(".post_content") %>
  <%= text_field_tag :user_key, @user_key, placeholder: t(".user_name") %>
  <%= submit_tag t(".search"), class: "btn btn-info" %>
<% end %>

app/views/posts_manager/_update.html.erb
<%= post.content.html_safe %>

app/views/posts_manager/bulk_destroy.js.erb
<% if @status == 200 %>
  <% @post_ids.each do |post| %>
    $('#post-detail-<%= post %>').fadeOut();
  <% end %>
<% else %>
  alert('<%= t "posts.destroy.has_error" %>');
<% end %>

app/views/posts_manager/create.js.erb
<% if @status == 200 %>
  $('#post-new').modal('toggle');
  $('.table-body').prepend('<%= j render("post", post: @post) %>');
  $('.modal-list').append('<%= j render("show",post: @post) %>');
  $('.modal-list').append('<%= j render("edit",post: @post) %>');
  $('.show-errors-create').html('');
  $('.post-title').val('');
  $('.post-content').val('');
<% else %>
  $('.show-errors-create').html('');
  <% @post.errors.full_messages.each do |message| %>
    $('.show-errors-create').append('<li><%= message %></li>');
  <% end %>
<% end %>

app/views/posts_manager/destroy.js.erb
<% if @status == 200 %>
  $('#post-detail-<%= @post.id %>').fadeOut();
<% else %>
  alert('<%= t "posts.destroy.has_error" %>');
<% end %>

app/views/posts_manager/index.html.erb
<button class="btn post-form-btn btn-info" data-toggle="modal"
  data-target="#post-new" title= "<%= t "static_pages.home.new_post" %>">
  <span class="glyphicon glyphicon-plus new-post-icon"><%= t ".create_new" %></span>
</button>
<%= render "new", post: @post, users: @users %>
<span class="search_form"><%= render "search_form" %></span>
<div class="csv-link">
</div>
<div class="clearfix"></div>
<div class="post-table">
  <%= form_tag destroy_posts_posts_manager_index_path, method: :delete, data: {confirm: t(".sure")}, class: "bulk-form", remote: true do %>
    <%= submit_tag "Delete all selected", class: "submit-bulk-destroy pull-right" %>
    <table class="table-striped posts-manager">
      <thead>
        <th class="head"><%= t ".title" %></th>
        <th class="head"><%= t ".content" %></th>
        <th class="head"><%= t ".user" %></th>
        <th class="head"><%= t ".id" %></th>
        <th class="head"></th>
        <th class="head"></th>
        <th></th>
      </thead>
      <tbody class="table-body">
        <% @posts.each do |post| %>
          <%= render "post", post: post%>
        <% end %>
      </tbody>
    </table>
  <% end %>
  <div class="modal-list">
    <%= render "modal_list", posts: Post.all %>
  </div>
  <div class="paginate pull-right"><%= render "paginate", posts: @posts %></div>
</div>

app/views/posts_manager/index.js.erb
$('.table-body').html('<%= j render("post_list", posts: @posts)%>');
$('.paginate').html('<%= j render("paginate", posts: @posts) %>');
$('.csv-link').html('<%= link_to "CSV Download", \
  posts_manager_index_path(:format => :csv, :post_key =>@post_key,\
  :user_key =>@user_key) %>')

app/views/posts_manager/search.js.erb
$('.table-body').html('<% @posts.each do |post| %>\
  <%= j render("post", post: post) %><% end %>');
$('.paginate').html('<%= j render("paginate", posts: @posts) %>');
$('.csv-link').html('<%= link_to "CSV Download", \
  posts_manager_search_path(:format => :csv, :post_key =>@post_key,\
  :user_key =>@user_key)%>')