config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => "/admin", as: "rails_admin"
  mount Ckeditor::Engine => "/ckeditor"
  root "static_pages#home"
  devise_for :users, controllers: {registrations: "registrations",
    omniauth_callbacks: "omniauth_callbacks"}

  resources :users, only: [:show] do
    member do
      get :following, :followers
    end
  end

  resources :posts, except: [:new, :edit, :index] do
    resources :comments, except: [:index, :new, :show]
  end

  resources :relationships, only: [:create, :destroy]
  resources :tags, only: :show
  resources :posts_manager, only: [:index, :create, :update] do
    collection do
      delete :destroy_posts
    end
  end
  get "/feed", to: "users#feed"
  post "search-post", to: "search#search_post"
  post "search-user", to: "search#search_user"
end

app/views/layouts/_footer.html.erb
<div class="footer">
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-sm-8 padding-top-10">
        <%= t ".from-framgia" %>
        <%= link_to t(".rails-tutorial"), "#" %> |
        <%= link_to t(".framgia-hanoi"), "#" %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<div class="row container-fluid">
  <nav class="header navbar navbar-fixed-top header-navigation font-transform-inherit">
    <li class="logo"><%= link_to image_tag("miniblog.png"), root_path, class: "mini-blog-logo" %></li>
    <ul class="pull-right">
      <% if user_signed_in? %>
        <li><%= link_to t(".my_blog"), current_user %></li>
        <li><%= link_to t(".following"), feed_path %></li>
        <li class="dropdown">
          <%= link_to current_user.full_name, "#", class: "dropdown-toggle",
              data: {toggle: "dropdown", target: "#"} %>
          <ul class="dropdown-menu">
            <li><%= link_to t(".edit_account"),
              edit_user_registration_path %></li>
            <li><%= link_to t(".sign_out"), destroy_user_session_path,
              method: :delete %></li>
          </ul>
        </li>
      <% else %>
        <li><%= link_to t(".log_in"), new_user_session_path %></li>
        <li><%= link_to t(".registration"), new_user_registration_path %></li>
      <% end %>
    </ul>
    <div class="post-form-div">
      <% if user_signed_in? && @post %>
        <button class="btn post-form-btn" data-toggle="modal"
          data-target="#post-form" title= "<%= t "static_pages.home.new_post" %>">
          <span class="glyphicon glyphicon-plus new-post-icon"></span>
        </button>
      <% end %>
    </div>
    <span class="post-search-form">
      <%= form_tag search_post_path, class: "search" do %>
        <table>
          <td><%= text_field_tag :keyword, nil, placeholder: t(".search_post") %></td>
          <td><%= submit_tag t(".search"), class: "submit-search btn-info" %></td>
        </table>
      <% end %>
    </span>
  </nav>
</div>
<div class="clearfix"></div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield :title %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application",
      media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application",
      "data-turbolinks-track": "reload" %>
    <%= render "layouts/shim" %>
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
  </head>
  <body>
    <%= render "layouts/header" %>
    <div class="container body-content">
      <div class="row main-body">
      <% flash.each do |message_type, message| %>
        <%= content_tag :div, message, class: "alert alert-#{message_type}" %>
      <% end %>

      <%= yield %>
      </div>
    </div>
    <div class="row page-footer">
      <%= render "layouts/footer" %>
    </div>
  </body>
</html>